# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # 月曜日の 01:00 (JST) に処理を実行する。
    # UTC の 17:00 は JST だと 01:00 。
    - cron: "00 17 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Deployment target"
        required: true
        default: "action"
        type: choice
        options:
          - action
          - staging
          - production
env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ vars.NOTION_DATABASE_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    environment: ${{ inputs.deployment_target || 'action' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-nodejs#nodejs%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%AE%E6%8C%87%E5%AE%9A
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: node setup
        run: |
          npm i

      - name: notionページの作成
        run: |
          npm run create
